spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/rash_project?hibernate.show_sql=true&hibernate.format_sql=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hit_user
    password: hitproject*e$%
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

